name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: zTig3r/workflows/.github/workflows/build-and-push-docker-image.yml@main
    with:
      project_name: 'faibot'
    secrets:
      CONFIG_REPO_PAT: ${{ secrets.DEPLOYMENT_REPO_PAT }}
